services:
  journal:
    build: 
      context: .
      args:
        - URL_PREFIX=/admin/journal
    container_name: journal
    env_file: .env.prod
    init: true
    networks:
      - bobya-bridge-network
    # depends_on:
    #   mariadb:
    #     condition: service_healthy

networks:
  bobya-bridge-network:
    external: true
